### ISSUE TITLE
What's the version of Julia that was used for this experiment?

### ISSUE THREAD

**Issue by Neo-101** [maximilian-gelbrecht/NPDEChaos#2]
Dr. Gelbrecht, I recently read your Article "Neural partial differential equations for chaotic systems" published in the New Journal of Physics.  

I found it very interesting and meaningful.  

So I downloaded your code from GitHub, but I encountered a problem when instantiating your Julia project package environment. 

Could you provide the version of Julia that was used for this experiment?

Thank you very much.

```
$ julia

(@v1.7) pkg> activate .
  Activating project at `~/Programming/NPDEChaos-master/NPDEChaos`

(NPDEChaos) pkg> st
      Status `~/Programming/NPDEChaos-master/NPDEChaos/Project.toml`
  [8e7c35d0] BlockArrays v0.11.1
  [35d6a980] ColorSchemes v3.9.0
  [3a865a2d] CuArrays v1.7.3
  [aae7a2af] DiffEqFlux v1.7.0
  [0c46a032] DifferentialEquations v6.11.0
  [31c24e10] Distributions v0.23.8
  [61744808] DynamicalSystems v1.3.0
  [587475ba] Flux v0.10.3
  [033835bb] JLD2 v0.1.14
  [429524aa] Optim v0.20.1
  [91a5bcdd] Plots v1.0.14
  [fa074d72] SeqData v0.1.0 `https://github.com/maximilian-gelbrecht/SeqData.jl.git#master`
  [9f7883ad] Tracker v0.2.6
  [e88e6eb3] Zygote v0.4.9
  [2f01184e] SparseArrays

(NPDEChaos) pkg> instantiate
┌ Warning: The active manifest file is an older format with no julia version entry. Dependencies may have been resolved with a different julia version.
└ @ ~/Programming/NPDEChaos-master/NPDEChaos/Manifest.toml:0
Precompiling project...
  ✗ CUDAdrv
  ✗ FFTW
  ✗ NNlib
  ✗ CodecZlib
  ✗ ColorSchemes
  ✗ RecursiveArrayTools
  ✗ ReverseDiff
  ✗ JLD2
  ✗ LombScargle
  ✗ DSP
  ✗ Tracker
  ✗ Zygote
  ✗ DiffEqBase
  ✗ CUDAnative
  ✗ Sundials
  ✗ BoundaryValueDiffEq
  ✗ SimpleDiffEq
  ✗ DiffEqJump
  ✗ DiffEqNoiseProcess
  ✗ OrdinaryDiffEq
  ✗ CuArrays
  ✗ DynamicalSystemsBase
  ✗ DelayDiffEq
  ✗ DiffEqCallbacks
  ✗ DiffEqFinancial
  ✗ StochasticDiffEq
  ✗ Flux
  ✗ DiffEqPhysics
  ✗ SteadyStateDiffEq
  ✗ DiffEqSensitivity
  ✗ ChaosTools
  ✗ MultiScaleArrays
  ✗ SeqData
  ✗ DiffEqFlux
  ✗ DifferentialEquations
  ✗ DynamicalSystems
  0 dependencies successfully precompiled in 22 seconds (146 already precompiled)
  36 dependencies errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the packages
```

**Comment by maximilian-gelbrecht** [comment]
Hey! 

Thanks for your interest in our paper. Please be aware that this repository is not actively maintained. It is just meant to archive the code. Unfortunately, I missed to include the Julia version in the Project.toml file, but given the time that I was working on it and our HPC state at the time, I am pretty sure that it was Julia 1.3.1. Julia and more so all of the libraries used changed a lot after this point, so it is understandable that you can run into some problems. 

Anyway, I am currently doing a lecture on similar topics and for that purpose I will reimplement most of this paper and upload as a new repository. I will inform you about it as soon as it is online. 

Best,
Max

**Comment by Neo-101** [comment]
Dr. Gelbrecht, thank you very much for your prompt and patient reply. 

I have never been exposed to the topic of solving chaotic partial differential equations with deep learning, and I have learned a lot through your article and code. 

I'm looking forward to your re-implementation.

Best, 
Neo-101

**Comment by maximilian-gelbrecht** [comment]
Hi, 

I set up a new repository for the updated version. The CGLE example is not yet updated, but the others are (and some more are there). I am still working on it a bit though. https://github.com/maximilian-gelbrecht/ChaoticNDETools.jl 

I also linked this repo in the readme, so with this I'll close this issue. 

Cheers
